Added ClockIn and ClockOut commands
CS2113-AY1819S1-F09-2/main pull request #113
Opened 2018-10-28 16:04 UTC by kianhong95

2018-10-28 16:39 UTC, AngWM approved these changes
Code looks good but you need to fix the test failing

2018-10-29 03:41 UTC, px1099 commented on src/seedu/addressbook/commands/employee/ClockOut.java
> +public class ClockOut extends Command {
I think this class should be named `EmployeeClockOutCommand` for consistency with the other class name

2018-10-29 03:42 UTC, px1099 commented on src/seedu/addressbook/commands/employee/ClockIn.java
> +public class ClockIn extends Command {
I think this class should be named `EmployeeClockInCommand` for consistency with the other class name

2018-10-29 03:53 UTC, px1099 commented on src/seedu/addressbook/commands/employee/ClockOut.java
> +public class ClockOut extends Command {
Or it can be named `AttendaceClockOutCommand`

2018-10-29 03:53 UTC, px1099 commented on src/seedu/addressbook/commands/employee/ClockIn.java
> +public class ClockIn extends Command {
Or it can be named `AttendaceClockOutCommand`

2018-10-29 08:12 UTC, px1099 requested changes
Can you refactor the name of the ClockIn and ClockOut command classes?

2018-10-29 10:09 UTC, px1099 approved these changes

2018-10-29 10:10 UTC, merged