Fixed Bugs in the code and instructions in the User Guide
CS2113-AY1819S1-F09-2/main pull request #144
Opened 2018-11-02 06:52 UTC by SalsabilTasnia

2018-11-03 11:28 UTC, px1099 requested changes

2018-11-03 11:28 UTC, px1099 commented on docs/UserGuide.adoc
> +System shows all the main dishes in the menu.
Line 112 seems to be incorrect

2018-11-03 11:28 UTC, px1099 commented on docs/UserGuide.adoc
> +System deletes the new food item in index 1 from the menu. +
Bad phrasing: "New food item"

2018-11-05 06:22 UTC, px1099 commented
So what does `viewallmenu` do?
It does not seem to be useful and user mistook it with `listmenu`

Or at least:
The key word `viewall` is used for viewing private details of a person in AB, and since `menu` don't hide its details, you should switch to the keyword `viewmenu`

2018-11-05 06:25 UTC, px1099 commented on docs/UserGuide.adoc
>  Format: `addmenu NAME p/PRICE type/TYPE [t/TAG]`
It is unclear that it allows multiple tags in the format

2018-11-05 06:26 UTC, px1099 commented on docs/UserGuide.adoc
>  Format: `addmenu NAME p/PRICE type/TYPE [t/TAG]`
From AB4 user guide:
Items with `…​` after them can be used multiple times including zero times e.g. `[t/TAG]…`​ can be used as   (i.e. 0 times), `t/friend`, `t/friend t/family`, etc.

2018-11-05 06:31 UTC, px1099 commented
You should add the 2 decimal digits restriction in the user guide

2018-11-05 06:35 UTC, px1099 commented on docs/UserGuide.adoc
> +System deletes menu item in index 1 from the menu. +
Should be adjusted to:
... from the menu of main dishes

2018-11-05 06:35 UTC, px1099 commented on docs/UserGuide.adoc
> +System deletes the menu item in index 1 from the menu. +
Should be adjusted to:
... from the menu of main dishes

2018-11-05 06:37 UTC, px1099 commented on docs/UserGuide.adoc
>  System deletes Cheese Fries in index 3 from the menu.
Should be adjusted to:
... from the displayed menu of items found with `Cheese Fries` keyword

2018-11-05 06:39 UTC, px1099 commented on docs/UserGuide.adoc
> +* The command is case insensitive.
The matched results are case insensitive

2018-11-06 04:53 UTC, SalsabilTasnia commented
> So what does `viewallmenu` do?
> It does not seem to be useful and user mistook it with `listmenu`
> 
> Or at least:
> The key word `viewall` is used for viewing private details of a person in AB, and since `menu` don't hide its details, you should switch to the keyword `viewmenu`

I am not changing this part since I am planning to get rid of `viewallmenu` command. I have not done it in this pr but I will do that in the following pr.

2018-11-06 07:16 UTC, px1099 approved these changes

2018-11-06 07:16 UTC, merged