add exceptions to handle overflow bugs
CS2113-AY1819S1-F09-2/main pull request #199
Opened 2018-11-10 10:44 UTC by kangmingtay

2018-11-10 11:19 UTC, px1099 requested changes

2018-11-10 11:19 UTC, px1099 commented on src/seedu/addressbook/parser/Parser.java
> +    public static final int PRICE_STRING_MAX_LENGTH = 5;
Too short
The price String is in the format $A.BC
For example: "$5.00" has the length of 5

2018-11-10 11:19 UTC, px1099 commented on src/seedu/addressbook/common/Messages.java
> +    public static final String MESSAGE_PRICE_LIMIT_EXCEEDED = "Price cannot be so large! ";
Incorrect message
First of all, we don't know if the input is even a number (the user can just input "asdfghjklsdfghjkl") or if it is indeed too large or not (the user type "$000000000000000001.00")
Should be changed to "The price input has cannot have more than <PRICE_STRING_MAX_LENGTH> digits/symbols/characters"

2018-11-10 11:19 UTC, px1099 commented on src/seedu/addressbook/parser/Parser.java
> +    public static final int PRICE_STRING_MAX_LENGTH = 5;
Recommendation: if the max price cannot exceed $10000.00, then max length should be 8 (length of $9999.99)

2018-11-11 02:46 UTC, kangmingtay commented
decided on another implementation, please refer to #200

2018-11-11 02:46 UTC, closed without merging