implementation of more member functions
CS2113-AY1819S1-F09-2/main pull request #99
Opened 2018-10-23 18:35 UTC by kangmingtay

add command to remove member from the member list

2018-10-24 06:49 UTC, kianhong95 requested changes
The three test methods: updateMemberPoints(), invalidMemberInOrder() and validMemberInOrder(), should assert some sort of expected output, otherwise the test would be redundant.

For updateMemberPoints() and validMemberInOrder() assert an expected output for them.

For invalidMemberInOrder(), if you don't want to use assertion can use something like:
@Test(expected = IndexOutOfBoundsException.class)
instead of throwing an Exception

2018-10-24 10:29 UTC, kianhong95 approved these changes

2018-10-25 03:26 UTC, px1099 commented on src/seedu/addressbook/data/Rms.java
> +    public Member findMemberInOrder(Member orderMember) {
~~Can you change the parameter type to ReadOnlyMember ?~~

2018-10-25 03:29 UTC, px1099 commented on src/seedu/addressbook/data/Rms.java
> +    public Member findMemberInOrder(Member orderMember) {
Better yet, you can create another overloading version that can except ReadOnlyMember instead

2018-10-25 03:33 UTC, px1099 commented on src/seedu/addressbook/data/Rms.java
> +            if((name == member.getName()) && (points == member.getPoints()) && (date == member.getDate())) {
you can make use of the isSameStateAs() method from ReadOnlyMember.java

2018-10-25 03:34 UTC, px1099 commented on src/seedu/addressbook/data/Rms.java
> +    public Member findMemberInOrder(Member orderMember) {
Changing the parameter type to ReadOnlyMember can cover both Member and ReadOnlyMember inputs

2018-10-25 03:37 UTC, px1099 commented on src/seedu/addressbook/data/member/MemberName.java
> +//    public static final String MESSAGE_NAME_CONSTRAINTS = "Member names should be spaces or alphanumeric characters";
(Unnecessary nitpicking) Should use /*   */ instead of using // for every line

2018-10-25 06:21 UTC, kangmingtay commented on src/seedu/addressbook/data/member/MemberName.java
> +//    public static final String MESSAGE_NAME_CONSTRAINTS = "Member names should be spaces or alphanumeric characters";
It is an intelliJ shortcut to block comment. Just highlight the area you wanna comment out and click [ ctrl + / ].

2018-10-25 09:11 UTC, merged